name: Code Review

on:
  workflow_dispatch:
    inputs:
      pullNumber:
        description: 'Number of the pull request to review'
        required: true
  pull_request_target:
    branches: [master, sdk-*]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.pullNumber || github.event.number }}
  cancel-in-progress: true

jobs:
  code_review:
    runs-on: ubuntu-18.04
    steps:
      - name: üëÄ Checkout
        uses: actions/checkout@v2
      - name: üë∑ Build and install SwiftLint
        run: |
          git clone https://github.com/realm/SwiftLint.git
          cd SwiftLint
          make build
          cp .build/x86_64-unknown-linux-gnu/release/swiftlint /usr/local/bin/
      - name: Make an artifact
        uses: actions/upload-artifact@v2
        with:
          name: swiftlint
          path: SwiftLint/.build
      - name: ‚ôªÔ∏è Restore node modules in tools
        uses: actions/cache@v2
        id: tools-modules-cache
        with:
          path: tools/node_modules
          key: ${{ runner.os }}-tools-modules-${{ hashFiles('tools/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-tools-modules-
      - name: üî¨ Reviewing a pull request
        run: bin/expotools code-review --pr ${{ github.event.inputs.pullNumber || github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.EXPO_BOT_GITHUB_TOKEN }}
